### ISSUE TITLE
Error with not guessing the Resolution

### ISSUE THREAD

**Issue by ngducphu** [opendatacube/odc-stac#112] opened 2023-03-27 03:11 UTC
Anyone has any idea how to fix this solution, I attached the code in the attachment for reference.

 

> ---------------------------------------------------------------------------
> 
> ValueError                                Traceback (most recent call last)
> ~\AppData\Local\Temp\ipykernel_32040\1725835586.py in <module>
>       1 ## Get Sentinel-1-RTC Data
>       2 assests = ['vh','vv']
> ----> 3 train_band_values=crop_yield_data.progress_apply(lambda x: get_sentinel_data(x['Longitude'], x['Latitude'],x['Season(SA = Summer Autumn, WS = Winter Spring)'],assests), axis=1)
>       4 vh = [x[0] for x in train_band_values]
>       5 vv = [x[1] for x in train_band_values]
> 
> ~\Anaconda3\lib\site-packages\tqdm\std.py in inner(df, func, *args, **kwargs)
>     812                 # on the df using our wrapper (which provides bar updating)
>     813                 try:
> --> 814                     return getattr(df, df_function)(wrapper, **kwargs)
>     815                 finally:
>     816                     t.close()
> 
> ~\Anaconda3\lib\site-packages\pandas\core\frame.py in apply(self, func, axis, raw, result_type, args, **kwargs)
>    8846             kwargs=kwargs,
>    8847         )
> -> 8848         return op.apply().__finalize__(self, method="apply")
>    8849 
>    8850     def applymap(
> 
> ~\Anaconda3\lib\site-packages\pandas\core\apply.py in apply(self)
>     731             return self.apply_raw()
>     732 
> --> 733         return self.apply_standard()
>     734 
>     735     def agg(self):
> 
> ~\Anaconda3\lib\site-packages\pandas\core\apply.py in apply_standard(self)
>     855 
>     856     def apply_standard(self):
> --> 857         results, res_index = self.apply_series_generator()
>     858 
>     859         # wrap results
> 
> ~\Anaconda3\lib\site-packages\pandas\core\apply.py in apply_series_generator(self)
>     871             for i, v in enumerate(series_gen):
>     872                 # ignore SettingWithCopy here in case the user mutates
> --> 873                 results[i] = self.f(v)
>     874                 if isinstance(results[i], ABCSeries):
>     875                     # If we have a view on v, we need to make a copy because
> 
> ~\Anaconda3\lib\site-packages\tqdm\std.py in wrapper(*args, **kwargs)
>     807                     # take a fast or slow code path; so stop when t.total==t.n
>     808                     t.update(n=1 if not t.total or t.n < t.total else 0)
> --> 809                     return func(*args, **kwargs)
>     810 
>     811                 # Apply the provided function (in **kwargs)
> 
> ~\AppData\Local\Temp\ipykernel_32040\1725835586.py in <lambda>(x)
>       1 ## Get Sentinel-1-RTC Data
>       2 assests = ['vh','vv']
> ----> 3 train_band_values=crop_yield_data.progress_apply(lambda x: get_sentinel_data(x['Longitude'], x['Latitude'],x['Season(SA = Summer Autumn, WS = Winter Spring)'],assests), axis=1)
>       4 vh = [x[0] for x in train_band_values]
>       5 vv = [x[1] for x in train_band_values]
> 
> ~\AppData\Local\Temp\ipykernel_32040\270945426.py in get_sentinel_data(longitude, latitude, season, assests)
>      30     items.reverse()
>      31 
> ---> 32     data = stac_load([items[1]],bands=bands_of_interest, patch_url=pc.sign, bbox=bbox_of_interest).isel(time=0)
>      33 
>      34     for item in items:
> 
> ~\Anaconda3\lib\site-packages\odc\stac\_load.py in load(items, bands, groupby, resampling, dtype, chunks, pool, crs, resolution, anchor, geobox, bbox, lon, lat, x, y, like, geopolygon, progress, fail_on_error, stac_cfg, patch_url, preserve_original_order, **kw)
>     492 
>     493     if gbox is None:
> --> 494         raise ValueError("Failed to auto-guess CRS/resolution.")
>     495 
>     496     if chunks is not None:
> 
> ValueError: Failed to auto-guess CRS/resolution.

`
[Script using odc-stac module.docx](https://github.com/opendatacube/odc-tools/files/11074261/Script.using.odc-stac.module.docx)
[Crop_Yield_Data.csv](https://github.com/opendatacube/odc-tools/files/11074264/Crop_Yield_Data.csv)

**Comment by SpacemanPaul** [comment] 2023-03-30 01:22
odc-stac is no longer part of the odc-tools repository.  Moving this to the odc-stac repo.

**Comment by Kirill888** [comment] 2023-03-30 05:19
@ngducphu please provide more information

1. what version of the `odc-stac` library you are using and how it was installed (conda/pip)
2. what data are you trying to access (from what STAC catalog, which collection, sample query)
3. what versions of other libraries are installed, most likely this is a duplicate of #106 and is related to mismatch of versions of projection extension between the data and software developed outside of this repository, see https://github.com/stac-utils/pystac/issues/448

**Comment by Kirill888** [comment] 2023-07-08 08:37
pretty sure this was due to projection extension version mismatch between software and data. This has been fixed upstream in `pystac`.

**Closed as completed by Kirill888** 2023-07-08 08:37 UTC
